In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

***Load the training data into feature matrix, class labels, and event ids***

In [4]:
from proj1_helpers import *
from functions import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

# Correction format de tx et y
tx = np.c_[np.ones((y.shape[0], 1)), tX]
y = np.expand_dims(y, axis=1)

In [5]:
print(y)

[[ 1.]
 [-1.]
 [-1.]
 ...
 [ 1.]
 [-1.]
 [-1.]]


***Code***

Le set est déjà divisé en training set et en validation set.
- Bootstrap
- K fold cross validation
- LOOCV
- logistic regression

In [6]:
##### Least squares test

loss, w = least_squares(y, tx)
print("Loss : \n", loss)
print("Weight : \n", w)

Loss : 
 [[0.3394456]]
Weight : 
 [[-3.60658249e-01]
 [ 7.23002324e-05]
 [-7.14479558e-03]
 [-6.24050466e-03]
 [-4.77093981e-04]
 [-3.08362917e-03]
 [ 4.49414410e-04]
 [-2.38156623e-02]
 [ 3.42160677e-01]
 [-1.09967260e-04]
 [-2.84138692e+00]
 [-2.16217554e-01]
 [ 9.55439870e-02]
 [ 4.52045508e-02]
 [ 2.84995341e+00]
 [-2.62719969e-04]
 [-9.95642542e-04]
 [ 2.85442758e+00]
 [-3.54662741e-04]
 [ 8.49821611e-04]
 [ 3.69247840e-03]
 [ 2.18113351e-04]
 [-5.00574858e-04]
 [-2.11522352e-01]
 [-2.18882120e-04]
 [ 2.01549537e-04]
 [ 3.43135865e-04]
 [-6.98404092e-05]
 [-6.58071021e-03]
 [-1.18306604e-02]
 [ 2.84063441e+00]]


In [8]:
##### GD/SGD test

gamma = 0.01
max_iters = 10
w = np.zeros((tx.shape[1], 1))

loss, w = least_squares_SGD(y, tx, w, max_iters, gamma)
print("Loss : \n", loss)
print("Weight : \n", w)

SGD(0/9): loss=75384.09771947966
SGD(1/9): loss=7324002781.218479
SGD(2/9): loss=409912782058037.0
SGD(3/9): loss=3.5884571086974755e+19
SGD(4/9): loss=1.8981792206686396e+24
SGD(5/9): loss=1.6565657034980044e+29
SGD(6/9): loss=1.6764071134194084e+34
SGD(7/9): loss=1.8436834098224452e+39
SGD(8/9): loss=2.4971252717485623e+41
SGD(9/9): loss=9.578012482131268e+45
Loss : 
 9.578012482131268e+45
Weight : 
 [[ 1.62196501e+39]
 [ 1.95818829e+41]
 [ 1.29650938e+40]
 [ 1.40457346e+41]
 [ 5.85915254e+40]
 [-1.61931736e+42]
 [-1.61912066e+42]
 [-1.61931954e+42]
 [ 4.49109182e+39]
 [ 9.96306604e+39]
 [ 1.71842447e+41]
 [ 2.25504870e+39]
 [ 1.30174701e+38]
 [-1.61931890e+42]
 [ 5.11422797e+40]
 [-1.42858595e+38]
 [-3.16459328e+39]
 [ 7.11187364e+40]
 [-2.21882763e+39]
 [ 3.04465587e+39]
 [ 2.24803906e+40]
 [ 2.51825299e+39]
 [ 2.28380180e+41]
 [ 1.62298891e+39]
 [ 4.95407792e+40]
 [ 2.51274526e+39]
 [-1.20807691e+39]
 [-1.61927952e+42]
 [-1.61932007e+42]
 [-1.61932304e+42]
 [ 4.95814306e+40]]


In [10]:
##### Ridge test
lambda_ = 0.01
loss, w = ridge_regression(y, tX, lambda_)

print("Loss : \n", loss)
print("Weight : \n", w)

Loss : 
 [[0.34008118]]
Weight : 
 [[ 1.10267635e-04]
 [-7.48959311e-03]
 [-5.31682031e-03]
 [-9.73425196e-04]
 [-2.32248396e-02]
 [ 4.85195515e-04]
 [-2.61163439e-02]
 [ 2.66432070e-01]
 [-4.28653891e-05]
 [ 5.00572657e-03]
 [-1.90711597e-01]
 [ 9.46549961e-02]
 [ 6.42350490e-02]
 [ 3.35773788e-03]
 [-3.52599679e-04]
 [-1.05540028e-03]
 [ 6.83828569e-03]
 [-5.21642984e-04]
 [ 9.42197453e-04]
 [ 3.96216945e-03]
 [ 3.67255443e-04]
 [-5.94005461e-04]
 [-2.62135617e-01]
 [-7.57843142e-04]
 [ 4.52373725e-04]
 [ 6.77511514e-04]
 [-1.28423258e-03]
 [-4.51814512e-03]
 [-9.17206052e-03]
 [-5.14913250e-03]]


In [11]:
#### Logistic regression test
gamma = 0.01
max_iters = 2
w = np.zeros((tx.shape[1], 1))

loss, w = log_reg(y.T, tx, w0, max_iters, gamma)

print("Loss : \n", loss)
print("Weight : \n", w)

NameError: name 'w0' is not defined

In [15]:
##### Penalized logistic regression test

gamma = 0.01
max_iters = 2
lambda_ = 0.01
w0 = np.zeros((tX.shape[1], 1))
loss, w = reg_log_reg(y, tX, lambda_, w0, max_iters, gamma)

print("Loss : \n", loss)
print("\n")
print("Weight : \n", w)

MemoryError: 

In [31]:
print(tx)

[[   1.     138.47    51.655 ...    1.24    -2.475  113.497]
 [   1.     160.937   68.768 ... -999.    -999.      46.226]
 [   1.    -999.     162.172 ... -999.    -999.      44.251]
 ...
 [   1.     105.457   60.526 ... -999.    -999.      41.992]
 [   1.      94.951   19.362 ... -999.    -999.       0.   ]
 [   1.    -999.      72.756 ... -999.    -999.       0.   ]]


## Generate predictions and save ouput in csv format for submission:

In [3]:
DATA_TEST_PATH = 'test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [4]:
OUTPUT_PATH = 'output.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

NameError: name 'weights' is not defined